name: Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5

jobs:
  run-script:
    name: Run main script
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install packages
        shell: bash
        run: deno install

      - name: Run script
        shell: bash
        run: deno run --allow-net --allow-read --allow-env src/main.ts
        env:
          PAGERDUTY_API_TOKEN: ${{ secrets.PAGERDUTY_API_TOKEN }}
          ESCALATION_POLICY_ID: ${{ secrets.ESCALATION_POLICY_ID }}
